#!/usr/bin/env python 
# -*- coding:utf-8 -*-
#
# @name:    Wascan - Web Application Scanner
# @repo:    https://github.com/m4ll0k/Wascan
# @author:  Momo Outaadi (M4ll0k)
# @license: See the file 'LICENSE.txt

from re import search,I 

def modsecurity(headers,content):
	_ = False
	for header in headers.items():
		_ |= search(r'Mod_Security|NOYB',header[1],I) is not None
		if _:break
	_ |= search(r'This error was generated by Mod_Security',content) is not None
	if _ : 
		return "ModSecurity: Open Source Web Application Firewall (Trustwave)"